language: ruby
rvm:
  - 2.3.3
dist: xenial
os: linux

script: "bundle exec rake"

install: bundle install --retry=3 --jobs=3

gemfile:
  - gemfiles/rails_4.gemfile
  - gemfiles/rails_5.gemfile
  - gemfiles/rails_6.gemfile

deploy:
  provider: rubygems
  api_key: $RUBYGEMS_API_KEY
  gem: jsonapi_compliable
  on:
    tags: true
    repo: jsonapi-suite/jsonapi_compliable
